accelerating_at_crosswalk: 4397
accelerating_at_stop_sign: 9382
accelerating_at_stop_sign_no_crosswalk: 2915
accelerating_at_traffic_light: 36796
accelerating_at_traffic_light_with_lead: 2146
accelerating_at_traffic_light_without_lead: 33815
behind_bike: 4254
behind_long_vehicle: 103371
behind_pedestrian_on_pickup_dropoff: 2121
changing_lane: 2363
changing_lane_to_left: 1284
changing_lane_to_right: 1079
changing_lane_with_lead: 3
changing_lane_with_trail: 50
crossed_by_bike: 60
crossed_by_vehicle: 670
following_lane_with_lead: 14483
following_lane_with_slow_lead: 194441
following_lane_without_lead: 595564
high_lateral_acceleration: 80119
high_magnitude_speed: 4671331
low_magnitude_speed: 938833
medium_magnitude_speed: 4889547
near_barrier_on_driveable: 192129
near_construction_zone_sign: 249607
near_high_speed_vehicle: 361460
near_long_vehicle: 960492
near_multiple_bikes: 76
near_multiple_pedestrians: 17740
near_multiple_vehicles: 237957
near_pedestrian_at_pickup_dropoff: 1914851
near_pedestrian_on_crosswalk: 8862866
near_pedestrian_on_crosswalk_with_ego: 61942
near_trafficcone_on_driveable: 492135
on_all_way_stop_intersection: 274703
on_carpark: 127598
on_intersection: 8545881
on_pickup_dropoff: 8211134
on_stopline_crosswalk: 362473
on_stopline_stop_sign: 593737
on_stopline_traffic_light: 1967343
on_traffic_light_intersection: 5892893
starting_high_speed_turn: 10389
starting_left_turn: 68337
starting_low_speed_turn: 7577
starting_protected_cross_turn: 21612
starting_protected_noncross_turn: 56570
starting_right_turn: 80389
starting_straight_stop_sign_intersection_traversal: 33972
starting_straight_traffic_light_intersection_traversal: 32976
starting_u_turn: 340
starting_unprotected_cross_turn: 49481
starting_unprotected_noncross_turn: 21063
stationary: 18474502
stationary_at_crosswalk: 6646
stationary_at_traffic_light_with_lead: 518426
stationary_at_traffic_light_without_lead: 1322141
stationary_in_traffic: 3764916
stopping_at_crosswalk: 23014
stopping_at_stop_sign_no_crosswalk: 7907
stopping_at_stop_sign_with_lead: 1568
stopping_at_stop_sign_without_lead: 10886
stopping_at_traffic_light_with_lead: 1568
stopping_at_traffic_light_without_lead: 6848
stopping_with_lead: 13163
traversing_crosswalk: 945766
traversing_intersection: 5942030
traversing_pickup_dropoff: 3801387
traversing_traffic_light_intersection: 4854749
waiting_for_pedestrian_to_cross: 41893
