accelerating_at_stop_sign: 13
accelerating_at_traffic_light: 295
accelerating_at_traffic_light_without_lead: 171
behind_long_vehicle: 6211
behind_pedestrian_on_pickup_dropoff: 187
changing_lane: 23
changing_lane_to_right: 23
crossed_by_vehicle: 1
following_lane_with_slow_lead: 8423
following_lane_without_lead: 18295
high_lateral_acceleration: 690
high_magnitude_speed: 33517
low_magnitude_speed: 41646
medium_magnitude_speed: 103605
near_barrier_on_driveable: 543
near_construction_zone_sign: 8644
near_high_speed_vehicle: 729
near_long_vehicle: 28066
near_multiple_vehicles: 4064
near_pedestrian_at_pickup_dropoff: 161486
near_pedestrian_on_crosswalk: 724223
near_pedestrian_on_crosswalk_with_ego: 2208
near_trafficcone_on_driveable: 25020
on_all_way_stop_intersection: 609
on_carpark: 3240
on_intersection: 84625
on_pickup_dropoff: 824169
on_stopline_crosswalk: 3477
on_stopline_stop_sign: 649
on_stopline_traffic_light: 21463
on_traffic_light_intersection: 75179
starting_high_speed_turn: 110
starting_left_turn: 484
starting_low_speed_turn: 16
starting_protected_cross_turn: 106
starting_unprotected_cross_turn: 378
stationary: 1123863
stationary_at_crosswalk: 29
stationary_at_traffic_light_with_lead: 25404
stationary_at_traffic_light_without_lead: 14929
stationary_in_traffic: 195352
stopping_at_crosswalk: 186
stopping_at_stop_sign_with_lead: 47
stopping_at_traffic_light_with_lead: 47
stopping_with_lead: 349
traversing_crosswalk: 8933
traversing_intersection: 21719
traversing_pickup_dropoff: 260916
traversing_traffic_light_intersection: 38890
waiting_for_pedestrian_to_cross: 1629
