_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: 'all'

scenario_types:                     # List of scenario types to include
- near_long_vehicle
- traversing_crosswalk
- on_stopline_traffic_light
- low_magnitude_speed
- stationary_in_traffic
- on_pickup_dropoff
- traversing_pickup_dropoff
- on_stopline_stop_sign
- on_stopline_crosswalk
- near_pedestrian_at_pickup_dropoff
- stationary_at_traffic_light_with_lead
- stationary_at_traffic_light_without_lead
- following_lane_without_lead
- on_carpark
scenario_tokens:                    # List of scenario tokens to include

log_names:                    # Filter scenarios by log names
map_names:                          # Filter scenarios by map names

num_scenarios_per_type: 500       # Number of scenarios per type
limit_total_scenarios:              # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s:              # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m:         # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold:          # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold:           # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance:              # Value at or below which a speed change between two timepoints should be ignored as noise.


expand_scenarios: true             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: true         # Whether to remove scenarios where the mission goal is invalid
shuffle: true                      # Whether to shuffle the scenarios
